services:
  mini-rv32ima-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        ALL_PROXY: ${ALL_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        all_proxy: ${all_proxy:-}
        no_proxy: ${no_proxy:-}
    image: mini-rv32ima-dev:ubuntu
    container_name: mini-rv32ima-dev
    working_dir: /work
    volumes:
      - ../:/work
    environment:
      MINIRV32IMA_TARGET: ${MINIRV32IMA_TARGET:-everything}
      MINIRV32IMA_FIX_WGET: ${MINIRV32IMA_FIX_WGET:-1}

      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      ALL_PROXY: ${ALL_PROXY:-}
      NO_PROXY: ${NO_PROXY:-}
      http_proxy: ${http_proxy:-}
      https_proxy: ${https_proxy:-}
      all_proxy: ${all_proxy:-}
      no_proxy: ${no_proxy:-}

    stdin_open: true
    tty: true
